allowBuilds:
  '@railgun-community/waku-broadcaster-client-web': false
  '@railgun-community/wallet': false
  blake-hash: false
  bufferutil: false
  es5-ext: false
  esbuild: false
  keccak: false
  msgpackr-extract: false
  secp256k1: false
  sharp: false
  unrs-resolver: false
  utf-8-validate: false
  web3: false
  web3-bzz: false
  web3-shh: false

overrides:
  "@base-org/account": 2.2.0
